image: 192.168.66.59:5000/devops/dind-rabbitmq

variables:
  # Configure rabbitmq environment variables
  USER_NAME: admin
  PASSWORD: admin123

stages:
- test

check_import:
  stage: test
  services:
    - rabbitmq:3.6.6-management
  script:
    - rabbitmqadmin -H 172.16.22.74 -u "$USER_NAME" -p "$PASSWORD" export /home/rabbitmq-definition
    - rabbitmqadmin -H rabbitmq import /home/rabbitmq-definition
    - echo {"queues":[{"name":"notify_request_queue","vhost":"/dev","durable":true,"auto_delete":false,"arguments":{}}]} > /home/test.config
    - rabbitmqadmin -H rabbitmq import /home/test.config

  tags:
    - ci
