image: 192.168.66.59:5000/devops/dind-rabbitmq

variables:
  # Configure rabbitmq environment variables
  USER_NAME: admin
  PASSWORD: admin123

stages:
- test

check_import:
  stage: test
  services:
    - rabbitmq:3.6.6-management
  script:
    - docker run -id -p 15672:15672 --name rabbitmq rabbitmq:3.6.6-management 
    - rabbitmqadmin -H 172.16.22.74 -u "$USER_NAME" -p "$PASSWORD" export /home/rabbitmq-definition
    - rabbitmqadmin -H 192.168.66.59 -u "$USER_NAME" -p "$PASSWORD" import /home/rabbitmq-definition

  tags:
    - ci
